version: '2'
services:
  backend:
    image: mhenna/steps-for-cause:latest
    ports:
      - "5000:5000"
    links:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - ./mongo-volume:/data/db
    expose:
      - 27017